Missing logos, hiding tokens without data
redstone-finance/redstone-app pull request #2
Opened 2021-06-01 13:40 UTC by piotruda

2021-06-06 20:32 UTC, hatskier requested changes
Great Pull Request! I've added minor comments below.

2021-06-06 20:32 UTC, hatskier commented on src/components/Tokens/Tokens.vue
> +        if (['wNXM', 'BTMX', 'NPXS', 'MDX', 'AMP'].includes(symbol)) {
I think wNXM may be removed from this list. Its price is already fetching correctly

2021-06-06 20:32 UTC, hatskier commented on src/components/Sidebar/NavLink/NavLink.vue
> +    showHeader: { type: Boolean },
Don't you think it would be cleaner to define showHeader here as a computed property, where we can fetch data from vuex state (!state.sidebarClose || state.sidebarStatic)?

2021-06-06 20:32 UTC, hatskier commented on src/pages/Redstone/Token/Token.vue
> +const PROVIDER_LABELS = {
We can use _.startCase methods from "lodash" library to automate provider titles conversion

2021-06-07 07:57 UTC, piotruda commented on src/components/Sidebar/NavLink/NavLink.vue
> +    showHeader: { type: Boolean },
Would be much cleaner :)

2021-06-07 09:11 UTC, merged